### ISSUE TITLE
Faute dans la partie Métaclasses

### ISSUE THREAD

**Issue by BartholomewPanda** [entwanne/cours_python_avance#12]
Il y a une faute dans l'introduction de la partie Métaclasses :
"les fonctions ou même les classes sont des objet."

Il manque un "s" à objets.

**Comment by Vayel** [comment]
Cette faute a déjà été relevée [ici](https://github.com/entwanne/cours_python_avance/issues/9), mais merci quand même. ^^

**Comment by BartholomewPanda** [comment]
Désolé, c'est la faute d'entwanne (<3) =/...
