### ISSUE TITLE
Duck typing

### ISSUE THREAD

**Issue by Vayel** [entwanne/cours_python_avance#3]
Peut-être serait-il judicieux d'introduire au _duck typing_ dans la présentation ? C'est du moins ce dont semble vaguement parler le second paragraphe.

**Comment by entwanne** [comment]
Effectivement, je suis pour le moment passé très vite sur la présentation. Ce n'était pas le chapitre qui m'intéressait le plus et je voulais passer au vif du sujet tant que j'étais bien motivé.
Je suis donc bien conscient que l'entrée en matière est plutôt brute pour le moment, je vais me garder ça dans un coin de la tête pour m'en occuper après la rédaction des chapitres manquants. Sauf si tu veux t'en charger.

**Comment by Vayel** [comment]
Je doute avoir le temps dans l'immédiat, mais si je parviens à en dégager je ferai une PR.

**Comment by Vayel** [comment]
Comptes-tu revoir la présentation ?

**Comment by entwanne** [comment]
La présentation n'est pas figée, mais je ne suis pas sûr que parler du _duck typing_ ici soit pertinent.
En effet, ces mécanismes sont permis en Python grâce au _duck typing_, mais ils le sont dans d'autres langages via un typage structurel par exemple.
