### ISSUE TITLE
Organisation des fichiers

### ISSUE THREAD

**Issue by Vayel** [entwanne/cours_python_avance#5]
Il me semble plus pratique pour relire de suivre l'organisation suivante : 

```
src/
  presentation.md
  subscriptables.md
  ...
```

`subscriptables.md`, par exemple, serait de la forme : 

``` markdown
Un premier type d'objets très connus sont les objets subscriptables. 
Ce nom barbare regroupe tous les objets sur lesquels l'opérateur `[]` 
peut être utilisé, comme les chaînes de caractères, les listes, les tuples 
ou les dictionnaires.

Deux nouvelles catégories sont comprises dans les subscriptables : les 
indexables et les sliceables. Les premiers sont ceux pouvant être indexés 
avec des nombres entiers, les seconds pouvant l'être avec des `slice` 
(voir plus loin).

On parle plus généralement de séquence quand un objet est indexable et 
sliceable.

# C'est pas la taille qui compte

...

# Objets indexables

...

# ...
```

Avec les termes de ZdS, tu aurais un fichier (_i.e._ tes dossiers actuels) par extrait. ^^

**Comment by entwanne** [comment]
Je ne sais pas, j'aime bien le découpage actuel, je trouve ça plus pratique pour l'édition.
Pour la lecture, j'utilise plutôt un rendu PDF de l'ensemble.

**Comment by Vayel** [comment]
Comme tu veux. ^^

Par contre, serait-il possible d'inclure le PDF au dépôt ?

**Comment by entwanne** [comment]
Je vais réfléchir pour mettre un PDF de disponible quelque part, mais je ne pense pas le mettre sur le dépôt, ça serait difficile à maintenir.

**Comment by Vayel** [comment]
Désolé d'être chiant, mais maintenant que l'import/export a été rendu facile avec la ZEP-12, ne serait-il pas intéressant de copier directement dans le dépôt la structure obtenue lors de l'export ?

**Comment by entwanne** [comment]
Je ne me suis pas encore intéressé au portage sur ZDS.
