### ISSUE TITLE
Prendre en compte derniers retours beta

### ISSUE THREAD

**Issue by entwanne** [entwanne/cours_python_avance#6]
- Explications sur ce qu'est un proxy ;
- Inversion argument/paramètre ;
- Précisions Python 3.5 ;
- Formulation de « qui possède une méthode `__call__`  » ;
- Mieux expliciter l'application partielle de fonction.

https://zestedesavoir.com/forums/sujet/4648/notions-de-python-avancees/?page=3#p91139

**Comment by Vayel** [comment]
Ayant arrêté ma deuxième relecture aux décorateurs, souhaites-tu que je la poursuive jusqu'à la fin ?

**Comment by entwanne** [comment]
Si tu en as le courage, je veux bien, oui.
De mon côté, je vais déjà prendre en compte tes précédentes remarques et j'ouvrirai à nouveau la beta quand une nouvelle version sera disponible.

Je vais voir aussi si ça ne vaut pas le coup d'ajouter des chapitres, je pense à un sur les concepts de _hashable_ et _mutable_, et un second sur `isinstance`/`issubclass` est les classes abstraites.

**Comment by Vayel** [comment]
Introduire à la notion d'objet mutable me semble une fort bonne idée. Je ne connais pas celle de _hashable_.

Pour la relecture, je vais exporter l'archive de la version publiée, l'importer et mettre mes commentaires directement dans le tuto-clône, auquel tu seras ajouté comme auteur. Je ne ferai qu'insérer des blocs de citations, donc tu n'auras qu'à les enlever, faire des modifications si besoin, exporter le clône, et mettre à jour l'original à partir de l'archive. Ca te semble correct ?

**Comment by entwanne** [comment]
Les hashable, ce sont les types qui peuvent être stockés dans des `set` / utilisés comme clefs dans des dictionnaires.

Comme tu le souhaites pour la relecture, j'arriverai à me débrouiller dans tous les cas.
