### ISSUE TITLE
Accesseurs et descripteurs - commentaires

### ISSUE THREAD

**Issue by Vayel** [entwanne/cours_python_avance#7]
# L'attribut de Dana

> Ces deux méthodes prennent respectivement les mêmes paramètres (en plus de self) que les fonctions auxquelles elles correspondent. 

Je ne suis pas sûr que tu aies besoin du "respectivement".

> Quant à getattr, la chose est un pleu complexe

plus

> Il est en cela possible d'implémenter des attributs dynamiquement, en modifiant le comportement des méthodes : par exemple une condition sur le nom de l'attribut pour retourner une valeur particulière.

Un exemple de code pourrait aider, j'ai un peu bloqué là-dessus. En effet, on peut déjà créer des attributs dynamiquement sans modifier ces méthodes (`foo.bar = x` fonctionne, que `foo.bar` existe ou non). Mais j'imagine que par "condition sur le nom de l'attribut", tu entends un truc plus complexe que `if attr == "bar":`, du genre `if "bar" in attr:`.

> `raise AttributeError(name)`

Tu pourrais ajouter un commentaire dans le code pour dire qu'ici, comme on hérite directement d'`object`, qui n'a pas de méthode `__getattr__`, on lève une exception.

>  le **dict** n'aura plus besoin d'être instancié lors de la création d'un nouvel objet

Effectivement, `__dict__` n'existe pas. Mais du coup, c'est un peu chiant pour récupérer les attributs d'un objet, puisqu'il faut regarder si l'un existe, sinon l'autre. Ils ne font pas `__dict__ = __slots__` pour que le programmeur sache qu'il ne pourra "plus par défaut définir d'attributs autres sur l'objet que ceux décrits dans les slots" ?

> J'évoquais précédemment le comportement de **getattribute**, qui consiste à consulter le dictionnaire de l'objet puis de ces parents.

ses

> afin de savoir à quelle classe super fait référence

`super()` plutôt que `super` ?

> On recherche dans foo.**dict** la présence d'une clef 'bar', dont on retourne la valeur si la clef existe

Et dans `foo.__slots__` ?

---

J'ai eu un peu de mal avec cette histoire d'attributs dynamiques. A voir, mais il me semble plus clair de mettre le code avant, qu'on ait un exemple sous les yeux. Le code irait juste après le paragraphe : 

> Ces méthodes sont chargées de retourner la valeur de l'attribut demandé. Il est en cela possible d'implémenter des attributs dynamiquement, en modifiant le comportement des méthodes : par exemple une condition sur le nom de l'attribut pour retourner une valeur particulière.
# Les descripteurs

> Cependant, seul l'accès en lecture sera possible sur la classe, les opérations de modification et de suppression servant à remplacer ou supprimer le descripteur.

Je ne suis pas sûr de comprendre cela.

> ``` python
> # Dans le cas où on appellerait `Temperature.celsius`
> # On préfère retourner le descripteur lui-même
> ```

Je ne comprends pas pourquoi on fait cela. Probablement lié à la remarque précédente.
# Les propriétés

> `class my_property:`

Pourquoi pas `MyProperty` ?

> `@celsius.setter`

Je ne sais pas pourquoi, mais j'ai bloqué sur cette ligne. Peut-être indiquer en commentaire `# Identique à @(property(celsius).setter)` ?
# Les méthodes

> En fait, les méthodes sont des descripteurs vers les fonctions que vous définissez à l'intérieur de votre classe.

Il me semble intéressant de donner un exemple de code d'un tel descripteur, voire des trois (méthodes normales, de classe et statiques).

Ah ben en fait c'est le TP.
# TP : propriétés et méthodes

> J'ajouterais à cela un descripteur method qui reproduirait le comportement par défaut des méthodes en Python.

"J'ajouterai" ?

> Ces 3 descripteurs sont de type non-data

"trois" ?

> Notez que vous pouvez vous aider du type MethodType (from types import MethodType) pour créer vos bound methods.

Je ne suis pas sûr de comprendre à quoi ça sert. Est-ce équivalent au code ci-dessous ?

``` python
def method_type(func, first):
    def f(*args, **kwargs):
        return func(first, *args, **kwargs)
    return f
```

Le cas échéant, pourquoi ont-ils utilisé une classe ?

Il ne me semble pas déconnant d'intégrer au TP la fonction ci-dessus, de sorte que le lecteur comprenne bien cette histoire de préparation de fonction.

> `class my_staticmethod:`

Même remarque/question que plus haut sur le nommage.

Merci.

**Comment by Vayel** [comment]
@entwanne : à table !

**Comment by entwanne** [comment]
Je n'ai pas énormément le temps de prendre ça en compte pour le moment.
Merci pour les différentes remarques, je laisse ça en suspens jusqu'à ce que je trouve un peu de temps.

**Comment by Vayel** [comment]
Je peux te faire une PR si ça t'arrange, en faisant en sorte que mes commits correspondent aux différentes remarques, que tu puisses facilement sélectionner les corrections souhaitées.

**Comment by entwanne** [comment]
Oui je veux bien, merci.
